In [2]:
import numpy as np
import pandas as pd 

In [3]:
def getSeriesData(data, window_size, elementdim=1):
	n_pairs = len(data) - window_size
	xlist = [data[i:i+window_size] for i in range(n_pairs)]
	ylist = [data[i+window_size] for i in range(n_pairs)]
	
	x = np.array(xlist, dtype=np.float32)
	y = np.array(ylist, dtype=np.float32)
	
	return x, y

In [4]:
x, y = getSeriesData([1,2,3,4,5,6,7,8,9,10], 3)
print(x)
print(y)

[[1. 2. 3.]
 [2. 3. 4.]
 [3. 4. 5.]
 [4. 5. 6.]
 [5. 6. 7.]
 [6. 7. 8.]
 [7. 8. 9.]]
[ 4.  5.  6.  7.  8.  9. 10.]


In [5]:
def getSeriesData(data, x_size, y_size):
    '''
    window_size 만큼의 데이터로 다음 데이터를 예측하기 위한 학습데이터 생성
    :param data: [1,2,3,4,5,6,7]
    :param x_size: X데이터의 window 사이즈
    :param y_size: Y데이터의 window 사이즈
    :return: x=[[1,2,3], [2,3,4], [3,4,5]]  if x_size=3
    :return: y=[  [4,5],   [5,6],   [6,7]]  if y_size=2
    '''
    n_pairs = len(data) - (x_size + y_size) + 1 # (x,y) pair 개수
    xlist = [data[i:i+x_size] for i in range(n_pairs)]
    ylist = [data[i+x_size:i+x_size+y_size] for i in range(n_pairs)]
    x = np.array(xlist, dtype=np.float32)
    y = np.array(ylist, dtype=np.float32)
    return x, y

In [6]:
## 데이터생성 테스트하기 
x, y = getSeriesData([i for i in range(0, 11)], 3, 2) #X는 3일, Y는 2일
print(x)
print(y)

[[0. 1. 2.]
 [1. 2. 3.]
 [2. 3. 4.]
 [3. 4. 5.]
 [4. 5. 6.]
 [5. 6. 7.]
 [6. 7. 8.]]
[[ 3.  4.]
 [ 4.  5.]
 [ 5.  6.]
 [ 6.  7.]
 [ 7.  8.]
 [ 8.  9.]
 [ 9. 10.]]


In [ ]:
X_SIZE = 3
Y_SIZE = 2
# 모델 구성하기
model = Sequential()
hidden_nodes = 60
model.add(LSTM(hidden_nodes, input_shape=(X_SIZE, 5),  # 5는 1개 데이터의 차수 (시가,종가, 고가, 저가, 거래량 등 총 5개)
               return_sequences=False))
model.add(Dropout(0.3))
model.add(Dense(Y_SIZE))
model.compile(loss='mean_squared_error', optimizer='adam')